var productListData = [
  [
    {'id': '1',
      'title': 'Apple iPhone 8 Plus 64GB 红色特别版 移动联通电信4G手机',
      'price': '5999.00',
      'comment': '943840',
      'img': 'mobile/mobile-1.jpg',
      'imglist': ['mobile/mobile-1-1.jpg', 'mobile/mobile-1-2.jpg', 'mobile/mobile-1-3.jpg', 'mobile/mobile-1-4.jpg'],
      'amount': '0'
    },
    {'id': '2',
      'title': 'Apple iPhone X',
      'price': '8316.00',
      'comment': '412054',
      'img': 'mobile/mobile-2.jpg',
      'imglist': ['mobile/mobile-2-1.jpg', 'mobile/mobile-2-2.jpg', 'mobile/mobile-2-3.jpg', 'mobile/mobile-2-4.jpg', 'mobile/mobile-2-5.jpg'],
      'amount': '0'
    },
    {'id': '3',
      'title': '小辣椒 红辣椒7X 4GB+64GB全面屏 人脸识别 双摄美拍 移动联通电信4G全网通 双卡双待 蓝色',
      'price': '899.00',
      'comment': '20264',
      'img': 'mobile/mobile-3.jpg',
      'imglist': ['mobile/mobile-3-1.jpg', 'mobile/mobile-3-2.jpg', 'mobile/mobile-3-3.jpg', 'mobile/mobile-3-4.jpg', 'mobile/mobile-3-5.jpg'],
      'amount': '0'
    },
    {'id': '4',
      'title': 'Apple iPhone 8 64GB 红色特别版 移动联通电信4G手机',
      'price': '4999.00',
      'comment': '544500',
      'img': 'mobile/mobile-4.jpg',
      'imglist': ['mobile/mobile-4-1.jpg', 'mobile/mobile-4-2.jpg', 'mobile/mobile-4-3.jpg', 'mobile/mobile-4-4.jpg'],
      'amount': '0'
    },
    {'id': '5',
      'title': '荣耀10 全面屏AI摄影手机 6GB+64GB 幻夜黑 全网通 移动联通电信4G 双卡双待',
      'price': '2599.00',
      'comment': '64480',
      'img': 'mobile/mobile-5.jpg',
      'imglist': ['mobile/mobile-5-1.jpg', 'mobile/mobile-5-2.jpg', 'mobile/mobile-5-3.jpg', 'mobile/mobile-5-4.jpg', 'mobile/mobile-5-5.jpg', 'mobile/mobile-5-6.jpg', 'mobile/mobile-5-7.jpg'],
      'amount': '0'
    },
    {'id': '6',
      'title': '荣耀畅玩7C 全面屏手机 全网通标配版 3GB+32GB 魅焰红 移动联通电信4G手机 双卡双待',
      'price': '899.00',
      'comment': '200071',
      'img': 'mobile/mobile-6.jpg',
      'imglist': ['mobile/mobile-6-1.jpg', 'mobile/mobile-6-2.jpg', 'mobile/mobile-6-3.jpg', 'mobile/mobile-6-4.jpg', 'mobile/mobile-6-5.jpg', 'mobile/mobile-6-6.jpg'],
      'amount': '0'
    },
    {'id': '7',
      'title': 'Apple iPhone6',
      'price': '2099.00',
      'comment': '501500',
      'img': 'mobile/mobile-7.jpg',
      'imglist': ['mobile/mobile-7-1.jpg', 'mobile/mobile-7-2.jpg', 'mobile/mobile-7-3.jpg'],
      'amount': '0'
    },
    {'id': '8',
      'title': '荣耀 畅玩7X 4GB+32GB 全网通4G全面屏手机 标配版 铂光金',
      'price': '1199.00',
      'comment': '540500',
      'img': 'mobile/mobile-8.jpg',
      'imglist': ['mobile/mobile-8-1.jpg', 'mobile/mobile-8-2.jpg', 'mobile/mobile-8-3.jpg', 'mobile/mobile-8-4.jpg'],
      'amount': '0'
    },
    {'id': '9',
      'title': '华为（HUAWEI） 荣耀10 手机 幻影蓝 全网通(6GB+64GB)',
      'price': '2699.00',
      'comment': '544500',
      'img': 'mobile/mobile-9.jpg',
      'imglist': ['mobile/mobile-9-1.jpg', 'mobile/mobile-9-2.jpg', 'mobile/mobile-9-3.jpg', 'mobile/mobile-9-4.jpg', 'mobile/mobile-9-5.jpg', 'mobile/mobile-9-6.jpg'],
      'amount': '0'
    },
    {'id': '10',
      'title': '荣耀9青春版 全网通 标配版 3GB+32GB 魅海蓝 移动联通电信4G全面屏手机 双卡双待',
      'price': '1099.00',
      'comment': '744500',
      'img': 'mobile/mobile-10.jpg',
      'imglist': ['mobile/mobile-10-1.jpg', 'mobile/mobile-10-2.jpg', 'mobile/mobile-10-3.jpg'],
      'amount': '0'
    },
    {'id': '11',
      'title': '小米(MI)移动电源2C 20000毫安 移动电源2/大容量充电宝 双USB输出 双向快充 聚合物 适用于平板/手机等',
      'price': '129.00',
      'comment': '997294',
      'img': 'battery/battery-1.jpg',
      'imglist': ['battery/battery-1-1.jpg', 'battery/battery-1-2.jpg', 'battery/battery-1-3.jpg', 'battery/battery-1-4.jpg'],
      'amount': '0'
    },
    {'id': '12',
      'title': '罗马仕（ROMOSS）sense6 加量版移动电源/充电宝 20000毫安大容量 白色 双USB输出 适用于平板/苹果/安卓手机',
      'price': '99.00',
      'comment': '1431859',
      'img': 'battery/battery-2.jpg',
      'imglist': ['battery/battery-2-1.jpg', 'battery/battery-2-2.jpg', 'battery/battery-2-3.jpg'],
      'amount': '0'
    },
    {'id': '13',
      'title': '飞利浦20000毫安移动电源/充电宝 超薄小巧聚合物 自带苹果认证线 DLP1201V白色 iPhone8/8P/iPhoneX适用',
      'price': '379.00',
      'comment': '16734',
      'img': 'battery/battery-3.jpg',
      'imglist': ['battery/battery-3-1.jpg', 'battery/battery-3-2.jpg', 'battery/battery-3-3.jpg'],
      'amount': '0'
    },
    {'id': '14',
      'title': '小米(MI) 10000毫安 新移动电源2 /充电宝 双向快充 超薄小巧便携 银色（新版）',
      'price': '79.00',
      'comment': '544500',
      'img': 'battery/battery-4.jpg',
      'imglist': ['battery/battery-4-1.jpg', 'battery/battery-4-2.jpg', 'battery/battery-4-3.jpg'],
      'amount': '0'
    },
    {'id': '15',
      'title': '大容量80000m超薄充电宝苹果oppo小米华为vivo手机通用快充50000移动电源20000毫安 酷炫黑（标配版）',
      'price': '78.00',
      'comment': '1589',
      'img': 'battery/battery-5.jpg',
      'imglist': ['battery/battery-5-1.jpg', 'battery/battery-5-2.jpg', 'battery/battery-5-3.jpg'],
      'amount': '0'
    },
    {'id': '16',
      'title': '罗马仕（ROMOSS）sense6Plus 移动电源/充电宝20000毫安 苹果/安卓手机/平板通用 数显屏 聚合物电芯 白色',
      'price': '89.00',
      'comment': '600829',
      'img': 'battery/battery-6.jpg',
      'imglist': ['battery/battery-6-1.jpg', 'battery/battery-6-2.jpg', 'battery/battery-6-3.jpg'],
      'amount': '0'
    },
    {'id': '17',
      'title': '飞利浦（PHILIPS） 充电宝超薄小巧10000毫安聚合物快充移动电源安卓苹果手机通用',
      'price': '139.00',
      'comment': '83561',
      'img': 'battery/battery-7.jpg',
      'imglist': ['battery/battery-7-1.jpg', 'battery/battery-7-2.jpg', 'battery/battery-7-3.jpg'],
      'amount': '0'
    },
    {'id': '18',
      'title': '罗马仕（ROMOSS）sense9 25000毫安充电宝大容量移动电源 3USB输出 聚合物 苹果/安卓手机/平板通用 白色',
      'price': '109.00',
      'comment': '168301',
      'img': 'battery/battery-8.jpg',
      'imglist': ['battery/battery-8-1.jpg', 'battery/battery-8-2.jpg', 'battery/battery-8-3.jpg'],
      'amount': '0'
    },
    {'id': '19',
      'title': '爱国者（aigo）E10000+充电宝超薄小巧便携10000毫安移动电源双输出适用于苹果华为小米 白色',
      'price': '79.00',
      'comment': '284356',
      'img': 'battery/battery-9.jpg',
      'imglist': ['battery/battery-9-1.jpg', 'battery/battery-9-2.jpg', 'battery/battery-9-3.jpg'],
      'amount': '0'
    },
    {'id': '20',
      'title': '华为（HUAWEI）20000毫安 充电宝/移动电源 9V2A快充版 黑色 适用于华为P20/Mate10/P10/Mate9/nova3e系列等',
      'price': '299.00',
      'comment': '45969',
      'img': 'battery/battery-10.jpg',
      'imglist': ['battery/battery-10-1.jpg', 'battery/battery-10-2.jpg', 'battery/battery-10-3.jpg'],
      'amount': '0'
    }
  ]
]

export {productListData}
